Fix lint error
Fixes the following lint error:

```
/Users/puckey/rg/_libraries/KotlinAudio/kotlin-audio/src/main/java/com/doublesymmetry/kotlinaudio/notification/NotificationManager.kt:159: Error: Call requires API level 24 (current min is 21): java.lang.Iterable#forEach [NewApi]
                config.buttons.forEach { button ->
                               ~~~~~~~
```

- Use for loop instead of `forEach` to avoid having to update minSdk level from 21 to 24.
- Remove unnecessary not empty array check